### ISSUE TITLE
Cannot install courgette

### ISSUE THREAD

**Issue by mathieugeissler** [canvaspixels/courgette#25]
Hi,

When I trying to execute `npm install courgette@2.10.3` postinstall failed

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! courgette@2.10.3 postinstall: `scripts/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the courgette@2.10.3 postinstall script.
`

My guess is node is missing before "scripts/setup.js"

Thank you

**Comment by canvaspixels** [comment]
Hi, apologies, completely missed this. Which platform are you on? Which version of npm and node are you using?

Thanks

**Comment by canvaspixels** [comment]
Closing this for now, please reopen if you're still getting the message. You can ignore most certain bits of the postinstall if they're causing issues with any combination of the following environment variables:

```
export IGNORE_COURGETTE_SAMPLE_SETUP=1
export IGNORE_COURGETTE_PACKAGE_JSON_SCRIPTS=1
export IGNORE_COURGETTE_CONF_SETUP=1
export IGNORE_COURGETTE_INSTALL_DRIVERS=1
npm install courgette
```

Or you can ignore altogether with npm install --ignore-scripts but you'll need webdriver manager to install one of the drivers for you though.
