### ISSUE TITLE
''Page object xxx not found" misleading error

### ISSUE THREAD

**Issue by Mariusz071** [canvaspixels/courgette#31]
One locator has been doubled up on 2 page objects or  page and component - test will crash with an error message that 'xxx page object not found' - xxx is the page object where locator was defined at the first point

**Comment by canvaspixels** [comment]
@Mariusz071 please could you provide more information in the format:

Current behaviour:

Expected behaviour:

**Comment by Mariusz071** [comment]
Actually the issue seems to be resolved, as now in this case throws an error "Map keys must be unique; "welcome title" is repeated", so it's all good and clear. 
Thanks!
