### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by evandro-machado** [canvaspixels/courgette#42]
Courgette is working on linux but it doesn't work on windows at the moment (didn't test mac).

**Comment by canvaspixels** [comment]
Hi @evandro-machado  Doesn't install or run? Do you have any more information / screenshots?

**Comment by evandro-machado** [comment]
Sure, to reproduce the error, in windows 10 Pro 64,  I did:

1. npm init
2. npm install courgette
![image](https://user-images.githubusercontent.com/11303091/61228452-50d6db80-a6f4-11e9-883e-5dd043f38e22.png)


I created a new pull request that fixes this problem:
https://github.com/canvaspixels/courgette/pull/44

**Comment by canvaspixels** [comment]
Thanks, please could you merge latest master into your branch as there was an issue with the travis setup. Once I get the green light i'll merge.

**Comment by evandro-machado** [comment]
Sure, I will do that, sorry it took so long.
