### ISSUE TITLE
Disable headless false doesn't work

### ISSUE THREAD

**Issue by evandro-machado** [canvaspixels/courgette#47]
If I run this command:
disableHeadless=false npm run-script ct

The browser appears anyway.

**Comment by canvaspixels** [comment]
Thanks, please could you merge latest master into your branch as there was an issue with the travis setup. Once I get the green light i'll merge.

Please make sure npm run lint passes, you might need to have a === in your PR.

There are also 3 configs in the repo that'll need updating:

1. One is for samples that you get on install to learn by example
2. One is to test the samples from within the repo
3. One for testing courgette with the react app (The one you've changed)

**Comment by evandro-machado** [comment]
Done.
