### ISSUE TITLE
Set cookie action triggers an InvalidCookieDomain error in firefox 78

### ISSUE THREAD

**Issue by pafontai** [canvaspixels/courgette#95]
Hi,

The set cookie action triggers an _InvalidCookieDomain_ error in firefox 78.
```
Tags: @courgette-bdd, @courgette-bdd-get-started-reusable-steps
Step: Given I am on the courgette homepage
    Steps group step: And I set the cookie 'MCPopupClosed' with value 'yes'
Location: reusable.steps
Feature: uiTests/features/courgette-homepage-bdd.feature:4
Error: InvalidCookieDomainError: Cookies may only be set for the current domain (courgette-testing.com)
    at World.theStepDef (/home/administrateur/test_courgette/node_modules/courgette/uiTestHelpers/hooks/loadSteps.js:115:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

The error comes from the 'domain:'localhost' line into the file
courgette/uiTestHelpers/stepDefinitions/actions/setCookie.js

When I force this value with the proper domain, all is ok

Is it able either to get automatically the domain from the URL to set the cookie domain or to pass it as a parameter ?

Best regards,
Patrice Fontaine

**Comment by canvaspixels** [comment]
Hi @pafontai good call. Feel free to submit a PR else I'll work on this asap. I guess it should parse the baseUrl set in the pomConfig. That sounds reasonable. I guess you also might want more flexibility in case you're dipping in and out of different sub-domains.

**Comment by canvaspixels** [comment]
Closing this for now
